name: Run Fear & Greed Bot

on:
  schedule:
    - cron: '0 5,19 * * *' # Runs at 5 AM and 7 PM UTC, or for Bulgarian time: 9 AM and 10 PM
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install dependencies
      run: npm install
    - name: Run script
      run: node src/notifier.js
      env:
        CMC_API_KEY: ${{ secrets.CMC_API_KEY }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
